server:
  port: 8001

spring:
  application:
    name: store-manage-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://43.138.20.232:3306/da_store?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Zu5L5ZObXrt1mpnvm0hHI9l9KXu6G21dSOVo6Y6gRptmIM/H/o6oCgx0z1oDvrTPy41CltCHAbR4kt9Iy6oJ7g==
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
       filter:
         config:
          enabled: true
       connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALAjbzbvpTENeJE0cAWseS9Tf6wxRJPrRO7rtMpv2ieA0woqnwU/2zGNaHCkFd7aab47965IiO1OME8QqJlAwDUCAwEAAQ==
       initial-size: 3
       min-idle: 3
       max-active: 20
       max-wait: 60000
       test-while-idle: true
       time-between-connect-error-millis: 60000
       min-evictable-idle-time-millis: 30000
       validation-query: select 'x'
       test-on-borrow: false
       test-on-return: false
       pool-prepared-statements: true
       max-pool-prepared-statement-per-connection-size: 20
       # DruidDataSource
       use-global-data-source-stat: false
       filters: stat,wall,slf4j
       connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
       time-between-log-stats-millis: 300000
       # DruidStatFilter
       web-stat-filter:
         enabled: true
         url-pattern: '/*'
         exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
       # DruidStatViewServlet
       stat-view-servlet:
         enabled: true
         url-pattern: '/druid/*'
         allow: 127.0.0.1,43.138.20.232
         reset-enable: false
         login-username: admin
         login-password: admin



